---
# Source: https://pre-commit.com/hooks.html
# pre-commit install
# pre-commit autoupdate
# detect-secrets scan > .secrets.baseline
# go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
# pre-commit run --all-files --verbose
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        description: Trims trailing whitespace.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
        exclude: .cache_ggshield
      - id: double-quote-string-fixer
      - id: debug-statements
        verbose: true
      - id: name-tests-test
        verbose: true
      - id: requirements-txt-fixer
        verbose: true
      - id: check-added-large-files
        args: [--maxkb=10000]
        verbose: true
        log_file: "true"
      - id: check-xml
        verbose: true
      - id: check-yaml
        verbose: true
        args: [--allow-multiple-documents]
        exclude: charts
      - id: check-json
        verbose: true
      - id: pretty-format-json
        args: [--autofix]
        verbose: true
      - id: detect-aws-credentials
        verbose: true
      # - id: detect-private-key
      #   verbose: true
      #   exclude: charts
      - id: check-merge-conflict
      # - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: ["--branch", "master"]
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: [--fix=auto]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        exclude: .secrets.baseline
        verbose: true
      - id: remove-tabs
        name: pre-commit-hooks (Lucas-C - useful git hooks)

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
      - id: setup-cfg-fmt
        name: setup-cfg-fmt (apply a consistent format to setup.cfg files)

  - repo: https://github.com/crate-ci/typos
    rev: v1.27.0
    hooks:
      - id: typos
        # - id: typos-docker
        name: typos (Finds and corrects spelling mistakes)
        args: [-v]
        exclude: charts|terraform/aws

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:  # Use yamlfix to fix yaml files
      - id: yamllint
        name: yamllint (linter for YAML files)
        exclude: charts

  - repo: https://github.com/PeterMosmans/jenkinslint
    rev: v1.0.0
    hooks:
      - id: jenkinslint
        name: jenkinslint (basic Jenkinsfile linter)

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
        name: reorder-python-imports (automatically reordering python imports)
        args: [--py39-plus, --add-import, from __future__ import annotations]
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        name: autopep8 (Style Guide Enforcement)

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (module for detecting secrets)
        args:
          ["--baseline", ".secrets.baseline"]   # OR # pragma: allowlist secret
          # - --baseline
          # - .secrets.baseline
        exclude: charts/|home-task-app-main/
        verbose: true

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        name: gitleaks
        description: Gitleaks is for detecting and preventing hardcoded secrets
        args: [--no-banner, --config=.gitleaks.toml]
        verbose: true

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.32.0
    hooks:
      # -   id: talisman-push
      - id: talisman-commit
        name: talisman (scans git for potential secrets, sensitive information)
        exclude: .pre-commit-config.yaml
        entry: cmd --githook pre-commit

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        name: dockerfilelint-hooks ( hook for checking Dockerfiles)
        stages: [pre-commit]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint
        args: [
          "--ignore",
          "DL3007",   # Using latest
          # '--ignore', 'DL3013',   # Pin versions in pip
          # '--ignore', 'DL3027',   # Do not use apt
          # '--ignore', 'DL3059',   # Docker `RUN`s shouldn't be consolidated
          # '--ignore', 'DL4006',   # Not related to alpine
          # '--ignore', 'SC1091',   # Useless check
          # '--ignore', 'SC2015',   # Useless check
          # '--ignore', 'SC3037',   # Not related to alpine
        ]
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: ["dockerfile"]
        entry: ghcr.io/hadolint/hadolint hadolint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: ["-l", "-i", "2", "-ci", "-sr", "-w"]
        verbose: true
      - id: shellcheck
        verbose: true

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # https://prettier.io/docs/en/options.html#parser
        files: ".json5$"

# - repo: https://github.com/norwoodj/helm-docs
#   rev: v1.13.1
#   hooks:
#     - id: helm-docs
#       name: helm-docs (auto-generates helm doc charts into markdown files)
#       args:
#         - --chart-search-root=charts  # search charts under the `charts` dir
#     - id: helm-docs-built
#       args:
#         - --chart-search-root=charts
#     - id: helm-docs-container
#       args:
#         - --chart-search-root=charts
#     - id: helm-docs-container
#       entry: jnorwood/helm-docs:x.y.z
#       args:
#         - --chart-search-root=charts
# - repo: https://github.com/gitguardian/ggshield  # need token for use
#   rev: v1.24.0
#   hooks:
#   - id: ggshield
#   - id: docker-ggshield
#     name: ggshield (CI environment to detect secrets)
#     always_run: true

# - repo: https://github.com/dmitri-lerko/pre-commit-docker-kustomize
#   rev: f3a8533
#   hooks:
#   -   id: kustomize
#       name: kustomize-development
#       args: [overlays/development]
#       verbose: false
#   -   id: kustomize
#       name: kustomize-staging
#       args: [overlays/staging]
#       verbose: false
#   -   id: kustomize
#       name: kustomize-production
#       args: [overlays/production]
#       verbose: false
#       name: post commit
#       always_run: true
